// Pre-recorded "Sorry, give me just a second." clips, one per UI language
// (public/audio/apology-<lng>.wav, generated by scripts/generate_apology_clips.py).
// They are local audio on purpose: they play while the model is rate-limited.
export const APOLOGY_CLIP_LANGUAGES = ["en", "es", "fr", "ja"] as const;

export function apologyClipUrl(language: string | undefined): string {
    const base = (language ?? "").toLowerCase().split("-")[0];
    const lng = (APOLOGY_CLIP_LANGUAGES as readonly string[]).includes(base) ? base : "en";
    return `/audio/apology-${lng}.wav`;
}

/** Plays the clip for the language; resolves when it ends or fails to play. */
export function playApologyClip(language: string | undefined): { done: Promise<void>; stop: () => void } {
    const audio = new Audio(apologyClipUrl(language));
    let finish: () => void = () => {};
    const done = new Promise<void>(resolve => {
        finish = resolve;
    });
    audio.addEventListener("ended", () => finish());
    audio.addEventListener("error", () => finish());
    Promise.resolve(audio.play()).catch(() => finish());
    return {
        done,
        stop: () => {
            audio.pause();
            finish();
        }
    };
}
